/*
 * sip_mpi_data.h
 *
 *  Created on: Jan 14, 2014
 *      Author: njindal
 */

#ifndef SIP_MPI_DATA_H_
#define SIP_MPI_DATA_H_

namespace sip{

class SIPMPIData {
public:

static const int MAX_STRING = 1024;	// Used for String identifiers of SAVE & RESTORE arrays

enum SIPMPIRequest {
	CREATE,
	DELETE,
	DELETE_ACK,
	GET,
	PUT,
	PUT_ACK,
	PUT_ACCUMULATE,
	PUT_ACCUMULATE_ACK,
	BARRIER,
	END_PROGRAM,
	SAVE_PERSISTENT,
	SAVE_PERSISTENT_ACK,
	RESTORE_PERSISTENT,
	RESTORE_PERSISTENT_ACK,
	SERVER_BARRIER,				// Message from SERVER master to other SERVERs for barrier
	SERVER_DELETE,				// Message from SERVER master to other SERVERs to delete array
	SERVER_END_PROGRAM, 		// Message from SERVER master to other SERVERs to end program
	SERVER_SAVE_PERSISTENT,		// Message from SERVER master to other SERVERs to save a persitent array
	SERVER_RESTORE_PERSISTENT	// Message from SERVER master to other SERVERs to restore a persistent array
};


enum SIPMPITags {
	WORKER_TO_SERVER_MESSAGE = 1122,
	WORKER_TO_SERVER_BLOCKID,
	WORKER_TO_SERVER_BLOCK_SIZE,
	WORKER_TO_SERVER_BLOCK_DATA,
	WORKER_TO_SERVER_DELETE,
	WORKER_TO_SERVER_SAVE_PERSISTENT,
	WORKER_TO_SERVER_RESTORE_PERSISTENT,
	WORKER_TO_SERVER_SAVE_PERSISTENT_ARRAY_IDENT,
	WORKER_TO_SERVER_RESTORE_PERSISTENT_ARRAY_IDENT,

	SERVER_TO_WORKER_BLOCK_SIZE,
	SERVER_TO_WORKER_BLOCK_DATA,

	SERVER_TO_WORKER_PUT_ACK,
	SERVER_TO_WORKER_PUT_ACCUMULATE_ACK,
	SERVER_TO_WORKER_SAVE_PERSISTENT_ACK,
	SERVER_TO_WORKER_RESTORE_PERSISTENT_ACK,
	SERVER_TO_WORKER_DELETE_ACK,

	SERVER_TO_SERVER_DELETE,
	SERVER_TO_SERVER_DELETE_ARRAY_ID,
	SERVER_TO_SERVER_BARRIER,
	SERVER_TO_SERVER_END_PROGRAM,
	SERVER_TO_SERVER_SAVE_PERSISTENT,
	SERVER_TO_SERVER_RESTORE_PERSISTENT,
	SERVER_TO_SERVER_SAVE_PERSISTENT_ARRAY_ID,
	SERVER_TO_SERVER_RESTORE_PERSISTENT_ARRAY_ID,
	SERVER_TO_SERVER_SAVE_PERSISTENT_ARRAY_IDENT,
	SERVER_TO_SERVER_RESTORE_PERSISTENT_ARRAY_IDENT
};

};

}



#endif /* SIP_MPI_DATA_H_ */
